# Trading Bot Configuration

# Database Configuration
database:
  host: "postgres"  # Docker service name
  port: 5432
  username: "trader"
  password: "secure_password"
  database: "trading_bot"
  
# Redis Configuration
redis:
  host: "redis"  # Docker service name
  port: 6379
  password: ""
  db: 0

# Trading Configuration
trading:
  initial_capital: 100000
  max_positions: 25        # Maximum concurrent positions
  max_position_size: 0.01  # 1% of portfolio per position
  stop_loss: 0.02         # 2% stop loss
  take_profit: 0.04       # 4% take profit
  max_drawdown: 0.15      # 15% maximum drawdown
  commission_rate: 0.001  # 0.1% commission
  slippage_rate: 0.0005   # 0.05% slippage
  
# Exchange Configuration
exchanges:
  binance:
    enabled: true
    testnet: false
    api_key: "${BINANCE_API_KEY}"
    api_secret: "${BINANCE_API_SECRET}"
    sandbox: true
  kucoin:
    enabled: true
    testnet: false
    api_key: "${KUCOIN_API_KEY}"
    api_secret: "${KUCOIN_API_SECRET}"
    sandbox: true
  bybit:
    enabled: true
    testnet: false
    api_key: "${BYBIT_API_KEY}"
    api_secret: "${BYBIT_API_SECRET}"
    sandbox: true
    
# Data Sources
# data:
#   symbols: 
#     - "BTC/USDT"
#     - "ETH/USDT" 
#     - "SOL/USDT"
#     - "ADA/USDT"
#     - "MATIC/USDT"
#   timeframe: "1h"
#   lookback_days: 365
#   cache_enabled: true
#   cache_dir: "data/cache"

# Machine Learning Configuration
ml:
  train_size: 0.7
  validation_size: 0.15
  test_size: 0.15
  random_state: 42
  auto_retrain_days: 7
  model_save_path: "storage/models"

# Strategy Configuration
strategies:
  strategy_allocation:
    momentum_strategy: 0.60    # 60% (was 45%) - better performing strategy
    mean_reversion: 0.30      # 30% (was 45%) - more conservative allocation
    ml_strategy: 0.0
    arbitrage_strategy: 0.10  # 10% (unchanged)
  mean_reversion:
    enabled: true
    lookback_period: 20
    entry_threshold: 1.5    # 1.5 (was 2.0) - more sensitive Bollinger Band
    exit_threshold: 0.5
    stop_loss: 0.02         # 2% (was 3%) - tighter stop loss
    take_profit: 0.025      # 2.5% (was 6%) - more achievable target
    
  ml_strategy:
    enabled: false
    model_type: "random_forest"
    retrain_frequency: 168  # hours (1 week)
    confidence_threshold: 0.6

  arbitrage_strategy:
    parameters:
      arbitrage_params:
        min_spread_threshold: 0.001  # 0.1% (was 0.4%) - more opportunities
        max_spread_threshold: 0.08   # 8% (unchanged)
        correlation_threshold: 0.60  # 0.6 (was 0.8) - more pairs qualify
        lookback_period: 50          # 50 (was 200) - faster calculation
        z_score_threshold: 0.5       # 0.5 (was 2.0) - more sensitive
        transaction_cost: 0.0005     # 0.05% (was 0.2%) - lower costs
    exchanges:
      binance:
        enabled: true
        api_key: "${BINANCE_API_KEY}"
        secret: "${BINANCE_API_SECRET}"
        sandbox: false
      kucoin:
        enabled: true
        api_key: "${KUCOIN_API_KEY}"
        secret: "${KUCOIN_API_SECRET}"
        sandbox: false
      bybit:
        enabled: true         # Enable ByBit for arbitrage
        api_key: "${BYBIT_API_KEY}"
        secret: "${BYBIT_API_SECRET}"
        sandbox: false

# Risk Management
risk:
  max_open_positions: 25    # 25 (was 5) - allow more positions for data collection
  max_daily_loss: 0.03      # 3% (was 5%) - tighter daily loss limit
  position_sizing_method: "percent_risk"
  default_risk_per_trade: 0.01  # 1% (was 2%) - lower risk per trade
  max_correlation: 0.7      # Add correlation limit
  volatility_filter: true   # Add volatility filter
  min_volume_ratio: 1.5     # Add volume filter
  
# Notifications
notifications:
  enabled: true
  telegram:
    enabled: false
    bot_token: ""
    chat_id: ""
  email:
    enabled: false
    smtp_server: ""
    smtp_port: 587
    username: ""
    password: ""
    to_email: ""
    
# API Configuration  
api:
  host: "0.0.0.0"
  port: 8000
  debug: false
  cors_origins: ["*"]
  
# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/trading_bot.log"
  max_file_size: 10485760  # 10MB
  backup_count: 5
  console: true
  database: true

# Monitoring
monitoring:
  enabled: true
  metrics_interval: 300    # 5 minutes
  health_check_interval: 60 # 1 minute
  
# Backtesting
backtesting:
  initial_capital: 100000
  commission_rate: 0.001
  slippage_rate: 0.0005
  start_date: "2023-01-01"
  end_date: "2024-12-31"
  
# Data Cleanup
cleanup:
  enabled: true
  run_hour: 2              # Run at 2 AM
  days_to_keep: 90         # Keep 90 days of data
  
# Security
security:
  max_api_requests_per_minute: 100
  require_api_key: false
  api_key: ""
  
# Development Settings
development:
  debug: true
  hot_reload: true
  profiling: false